### ISSUE TITLE
Please provide "Box - panels battery mount" as two seperate parts

### ISSUE THREAD

**Issue by jasc76** [aat-sentinel/AAT-lite-hardware#4]
I cant get them separated in Fusion....

**Comment by ShikOfTheRa** [comment]
Yes this no problem. I will do that first thing tomorrow

**Comment by ShikOfTheRa** [comment]
Seperated:

https://github.com/aat-sentinel/AAT-lite-hardware/tree/main/Extras/AAT%20battery%20panel%20mount
