### ISSUE TITLE
Pan Issue

### ISSUE THREAD

**Issue by Davierooker** [aat-sentinel/AAT-lite-hardware#5]
Hi, I've built and tested my tracker and when it works it is really good. However more often than not the pan stays facing North, although the tilt appears to be working. I've tested the pan in the simulator and it works as expected, so I'm not sure what is going on. The tracker appears to be getting telemetry OK because the tilt appears to working. I'm arming the plane next to the tracker, so don't know what else to try.

**Comment by ShikOfTheRa** [comment]
@whammer007

This is a really strange one – works ok in simulator, but intermittent yaw only in flight.
This makes we think the flight controller must be sending data if the tilt is working – but almost sounds like it is sending wrong yaw info. 
I am wondering if something has become an issue in iNAV during the changes up to the final 3.0 release version.

If you are able to save a log file as error414 indicated on RCG it would be most valuable in helping identify the cause…

What version iNav (assume that’s what is used)
What FC
Could you post a CLI dump

**Comment by Davierooker** [comment]
I did some more testing and found that sometimes the pan servo sometimes does not respond in the simulator, then after a power cycle responds properly. I carried out further testing as below:
I powered up the tracker and checked the servo operation was OK in the simulator. I then powered up the plane and waited for telemetry. I armed the plane and moved it beyond 10 metres. I repeated this 10 times. I have found that if the servo moves in the simulator, then it will track correctly.
I am using INAV 3.0 release version on various Matek FC's in this case an F411wse. 
I was unable to retrieve the tracker log as yet, but the signal strength was constant and the angle values were changing (even when not panning correctly).
I have attached the FC diff, although I'm not sure that it is INAV related...
[Drift 3.0.txt](https://github.com/aat-sentinel/AAT-lite-hardware/files/6708944/Drift.3.0.txt)

**Comment by ShikOfTheRa** [comment]
OK - helps a lot. I was really worried something changed in iNav. 
I think what you have said rules that out. Angles changing and also seeing it fail on the sim helps validate.

As it is same power supply for both servos, I think it is worth looking at these next: 
- Check servo voltage is OK - approx 5v
- Bad servo wire / crimp connector joint
- Bad solder joint on the pan servo pin header
- Bad servo
- Cracked PCB track - Atmega IC / Supply / GND to servo pin
- Bad solder joint on Atmega IC pin driving servo ( unlikely / unlucky)

If could check the first 3 and no fix I would be happy to send out another servo.


Great testing and many thanks for your time helping to diagnose.

**Comment by ShikOfTheRa** [comment]
Completely off topic - what are you thoughts on the drifter? I have always wanted to try a glider and it seems quite a good option for the calm days

**Comment by Davierooker** [comment]
The Drift is a cracking model, it flies really well. I run it with a 2S lion pack and it will fly for an hour. It can handle a bit of wind as well.

**Comment by ShikOfTheRa** [comment]
I'm tempted... I have a strix mini goblin running 2s and really like that one so it seems quite a good option.

**Comment by ShikOfTheRa** [comment]
Can you drop me an email @virtualpilot and I'll get a servo out to you. It seems most likely issue

**Comment by Davierooker** [comment]
I've checked the board for any damage (none) and decided to reflow the servo pins, I will test again tomorrow if the rain ever goes off. I have a spare MG995 servo that I can swap out to further troubleshoot if required. Thanks for all your help so far, I'll keep you posted.

**Comment by ShikOfTheRa** [comment]
Cheers!

The pan servo needs to be able to support 180 deg - so if yours doesn't could possibly swap the tilt servo to the pan position. If need one happy to send out.

**Comment by Davierooker** [comment]
Some follow up and test results from today.
I reflowed the servo headers - no change.
I replaced the servo with an identical brand new one I had - no change.
The next time it failed to pan, I power cycled the tracker and it immediately tracked straight at the target. So it would appear that this is at worst only a minor annoyance if it is cured by a power cycle of the tracker after launch. ( I was definitely overthinking this as I'm used to the U360GTS tracker which has way to many things that can go wrong and can be immensely frustrating to get right).
 One thing I did notice while testing was, occasionally when arming the "arm screen" on the video feed would not come up. (the plane would still arm) when this happened the tracker did not track AT ALL. The way to tell if it "sees" the plane is armed is that the Telemetry LED blinks once when the arm switch is triggered, if it stays solid while the arm switch is operated then it will not track. (but the plane will still arm) This definitely seems like an INAV issue, which is also resolved by power cycling the tracker so all good.
Thanks for your support.

**Comment by ShikOfTheRa** [comment]
Thanks again for the the testing. 

In all the time I have been flying I've never seen that issue or had to power cycle for servos. The only time I have had to do that is if I have changed planes where one was say NTSC and the other PAL. I think it works anyway if leave long enough.


The iNav one sounds interesting....
The blip is because Telemetry is not sent when armed screen is shown. This is expected.
No arming screen - I don't pay much attention to it really. I will install v3 on on my test copter and see what it does...
But if cycling the tracker fixes that - weird. Makes it not look like an iNav issue.

We'll keep looking at it from this end to see if can identify anything odd in iNav.

**Comment by Davierooker** [comment]
I managed to get some actual flight tests done yesterday, and the results were not good to say the least. The first and the last flight tracked perfectly, however the 20 or so launches in between resulted in no pan. The tilt was working on all flights, but not the pan. I tried the power cycle trick in flight, but that did not work at all. The heading on the display is about right and is changing as the plane flies around, but there is no response from the pan servo. It is receiving power as it is locked in the North position and resistance can be felt if I try to turn it.

**Comment by ShikOfTheRa** [comment]
Out of interest - can you advise what version firmware you are running on the board? Is it the one shipped with the board?
I am running 3.2.2 on mine which is the latest

**Comment by Davierooker** [comment]
I'm running 3.2.2 as well.
I tested again today with a different model with a Matek F411 wing FC. I only had 4 flights, but it tracked every one. The board on the other model was a Matek F411 WSE.

**Comment by ShikOfTheRa** [comment]
I am completely puzzled by this one!

If blue light is on it is receiving valid tracking info. There is error checking to verify data received is same as sent. 
If data is corrupt or no telemetry received, blue light goes out quickly.

Heading and tilt is sent in the same data packet, so if tilt is moving OK, it must be receiving heading info to too.
It is possible iNav is sending incorrect incorrect data. But...
 
Heading data is shown to be changing on the OLED display - so it seems that iNav is sending correct heading data and tracker is receiving heading data and also processing it to be able to display.

The pan / tilt uses same supply and as the pan servo seems locked it sound like it is receiving power and ground
This points towards an issue with the servo / servo drive code / servo drive circuit.
Servo replaced- so unlikely to a second one has same issue.

And flying with a different FC worked....
Seems no logic to how this is working/not working. Truly stumped.

If we need to do this to eliminate PCB this might be next option, but it doesn't seem like a hardware issue with PCB. 
Still trying to work though failure modes that would cause this...

**Comment by Davierooker** [comment]
Thanks for your help on this, it's really appreciated. I took the Drift back out this morning as the weather was great...no pan. I power cycled it a couple of times and it started panning. This happened for the 3 flights that I had. This is the model F411WSE FC that seems to be having the issue. I will report back any other findings with different FC's etc. as I fly them.

**Comment by ShikOfTheRa** [comment]
If the telemetry led is on, it should mean that the FC is sending data tracker can understand.
And if heading display changes and the power cycle fixes it mid flight it sounds like data sent is correct.
Working tilt supports this theory

I would expect if problem with the FC that the telemetry LED would not light at all. Also no tilt.

Let us know how the other boards work. I cannot think how The FC would only affect pan operation

**Comment by ShikOfTheRa** [comment]
Hi - did you have any further results from testing?

We have been unable to replicate this issue with the equipment we have but I have a couple of questions:
1 - what camera(s) do you use
2 - do you use dual camera input on the WSE ?

**Comment by Davierooker** [comment]
Hi,
I've had a few flights with different FC's and cameras which I will summarize below:

ZOHD Drift, Matek F411WSE, Runcam Split 3 lite = Very hit and miss with tracking.
ZOHD Dart, Matek F411 WSE, Caddx Starlight = Tracks OK.
Ranger 1600, Matek F722STD, Runcam Split 2 = Tracks OK
Mini Talon, Matek F405 Wing, Caddx Tarsier = Tracks OK
Vortigaunt, Matek F765 Wing, Caddx Tarsier = Tracks OK

With the exception of the drift, the models above have only been flown a handful of times so far.

Its kinda looking like the camera/video feed from the Runcam Split 3 lite setup?
I will test the drift with a different camera in it and feed back the results.

I have not used the dual input of the WSE.

**Comment by ShikOfTheRa** [comment]
Thanks for the feedback. As you say its helping narrow it down a little.

This is just a possibility I was thinking about last night…

During development of MWOSD I had issues with a few cameras that power up in one mode then changed to another  - usually NTSC before changing to PAL. This caused many issues because it detected NTSC signal so presumed it was an NTSC camera. 
The solution was to keep checking the signal and then change if necessary.

With the tracker it is not so easy to do this as it is not always a clean video signal.  Have to take into consideration poor  signal / loss of signal  and determining valid data which itself takes a few seconds. Not what you want at extremes or range!

So suggestions for now for the Split 3are are:
1 Always restart the tracker after the aircraft powered up and stabilised. 
2 Always have a good clean power feed to camera / VTX – this also can impact the telemetry.


We are looking at options to help mitigate this in software. It will take some time with plenty of testing by us first as it would be a change to the core telemetry capturing which has been tuned over the last 24 months. .


Worst case scenario - will have to get one to evaluate as this is the only such report we have recieved.

**Comment by ShikOfTheRa** [comment]
Can you try beta firmware here with your spilt camera?
It may help the issue..
https://github.com/aat-sentinel/AAT-lite-firmware

**Comment by Davierooker** [comment]
I'll give it a go as soon as the weather clears up.

**Comment by ShikOfTheRa** [comment]
Hello - just wondered if you ever had opportunity to test?

**Comment by Davierooker** [comment]
I've only had a handful of flights on the new firmware, so didn't think it was enough to report back. I did fly the "problem" model however and had no issues.

**Comment by ShikOfTheRa** [comment]
OK, no problem. I'll keep this open for now. Thanks for feedback and testing!

**Comment by Davierooker** [comment]
I managed to get 4 flights in today with 2 different models, no issues at all.

**Comment by ShikOfTheRa** [comment]
Awesome. I t seems @error414 has added a fix and improvement at same time.
